{"message": "invalid literal for int() with base 10: '123456akhjgfjhgf'", "time": "2020-06-29T21:23:18.080893", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: '123456akhjgfjhgf'"}
{"message": "invalid literal for int() with base 10: '123456akhj'", "time": "2020-06-29T21:26:50.051270", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: '123456akhj'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:44.267916", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:44.418533", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:48.072386", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:48.556353", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:48.838286", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:48.985351", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:49.142829", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:49.282798", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:49.410107", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:49.542202", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:49.661549", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:49.831646", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:49.985770", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:50.131705", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:50.373836", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:50.610868", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:51.131095", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:51.542534", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'gbar'", "time": "2020-06-30T17:34:51.748889", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'gbar'"}
{"message": "invalid literal for int() with base 10: 'test.bak'", "time": "2020-06-30T17:34:51.913047", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test.bak'"}
{"message": "invalid literal for int() with base 10: 'test.backup'", "time": "2020-06-30T17:34:52.066798", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test.backup'"}
{"message": "invalid literal for int() with base 10: 'test.bac'", "time": "2020-06-30T17:34:52.208189", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test.bac'"}
{"message": "invalid literal for int() with base 10: 'test.zip'", "time": "2020-06-30T17:34:52.355793", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test.zip'"}
{"message": "invalid literal for int() with base 10: 'test.tar'", "time": "2020-06-30T17:34:52.498721", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test.tar'"}
{"message": "invalid literal for int() with base 10: 'test.jar'", "time": "2020-06-30T17:34:52.659075", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test.jar'"}
{"message": "invalid literal for int() with base 10: 'test.log'", "time": "2020-06-30T17:34:52.838629", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test.log'"}
{"message": "invalid literal for int() with base 10: 'test.swp'", "time": "2020-06-30T17:34:52.976708", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test.swp'"}
{"message": "invalid literal for int() with base 10: 'test~'", "time": "2020-06-30T17:34:53.102589", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test~'"}
{"message": "invalid literal for int() with base 10: 'test.old'", "time": "2020-06-30T17:34:53.235572", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test.old'"}
{"message": "invalid literal for int() with base 10: 'test.~bk'", "time": "2020-06-30T17:34:53.359371", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test.~bk'"}
{"message": "invalid literal for int() with base 10: 'test - Copy'", "time": "2020-06-30T17:34:53.492714", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test - Copy'"}
{"message": "invalid literal for int() with base 10: 'test - Copy (2)'", "time": "2020-06-30T17:34:53.624598", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test - Copy (2)'"}
{"message": "invalid literal for int() with base 10: 'test - Copy (3)'", "time": "2020-06-30T17:34:53.752116", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test - Copy (3)'"}
{"message": "invalid literal for int() with base 10: 'testbackup'", "time": "2020-06-30T17:34:53.909048", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'testbackup'"}
{"message": "invalid literal for int() with base 10: 'Copy of test'", "time": "2020-06-30T17:34:54.053611", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'Copy of test'"}
{"message": "invalid literal for int() with base 10: 'Copy (2) of test'", "time": "2020-06-30T17:34:54.209205", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'Copy (2) of test'"}
{"message": "invalid literal for int() with base 10: 'Copy (3) of test'", "time": "2020-06-30T17:34:54.364671", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'Copy (3) of test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:54.645331", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:54.846435", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:55.056690", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:55.417137", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:55.581454", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:55.750424", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:55.879777", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'trace.axd'", "time": "2020-06-30T17:34:56.033185", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'trace.axd'"}
{"message": "invalid literal for int() with base 10: '.htaccess'", "time": "2020-06-30T17:34:56.270829", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: '.htaccess'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:56.421337", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:56.577675", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:56.832106", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:57.015833", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:57.165645", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:57.299304", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:57.436301", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:57.608173", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: '.env'", "time": "2020-06-30T17:34:57.819184", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: '.env'"}
