{"message": "invalid literal for int() with base 10: '123456akhjgfjhgf'", "time": "2020-06-29T21:23:18.080893", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: '123456akhjgfjhgf'"}
{"message": "invalid literal for int() with base 10: '123456akhj'", "time": "2020-06-29T21:26:50.051270", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: '123456akhj'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:44.267916", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:44.418533", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:48.072386", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:48.556353", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:48.838286", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:48.985351", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:49.142829", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:49.282798", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:49.410107", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:49.542202", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:49.661549", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:49.831646", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:49.985770", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:50.131705", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:50.373836", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:50.610868", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:51.131095", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:51.542534", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'gbar'", "time": "2020-06-30T17:34:51.748889", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'gbar'"}
{"message": "invalid literal for int() with base 10: 'test.bak'", "time": "2020-06-30T17:34:51.913047", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test.bak'"}
{"message": "invalid literal for int() with base 10: 'test.backup'", "time": "2020-06-30T17:34:52.066798", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test.backup'"}
{"message": "invalid literal for int() with base 10: 'test.bac'", "time": "2020-06-30T17:34:52.208189", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test.bac'"}
{"message": "invalid literal for int() with base 10: 'test.zip'", "time": "2020-06-30T17:34:52.355793", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test.zip'"}
{"message": "invalid literal for int() with base 10: 'test.tar'", "time": "2020-06-30T17:34:52.498721", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test.tar'"}
{"message": "invalid literal for int() with base 10: 'test.jar'", "time": "2020-06-30T17:34:52.659075", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test.jar'"}
{"message": "invalid literal for int() with base 10: 'test.log'", "time": "2020-06-30T17:34:52.838629", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test.log'"}
{"message": "invalid literal for int() with base 10: 'test.swp'", "time": "2020-06-30T17:34:52.976708", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test.swp'"}
{"message": "invalid literal for int() with base 10: 'test~'", "time": "2020-06-30T17:34:53.102589", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test~'"}
{"message": "invalid literal for int() with base 10: 'test.old'", "time": "2020-06-30T17:34:53.235572", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test.old'"}
{"message": "invalid literal for int() with base 10: 'test.~bk'", "time": "2020-06-30T17:34:53.359371", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test.~bk'"}
{"message": "invalid literal for int() with base 10: 'test - Copy'", "time": "2020-06-30T17:34:53.492714", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test - Copy'"}
{"message": "invalid literal for int() with base 10: 'test - Copy (2)'", "time": "2020-06-30T17:34:53.624598", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test - Copy (2)'"}
{"message": "invalid literal for int() with base 10: 'test - Copy (3)'", "time": "2020-06-30T17:34:53.752116", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test - Copy (3)'"}
{"message": "invalid literal for int() with base 10: 'testbackup'", "time": "2020-06-30T17:34:53.909048", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'testbackup'"}
{"message": "invalid literal for int() with base 10: 'Copy of test'", "time": "2020-06-30T17:34:54.053611", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'Copy of test'"}
{"message": "invalid literal for int() with base 10: 'Copy (2) of test'", "time": "2020-06-30T17:34:54.209205", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'Copy (2) of test'"}
{"message": "invalid literal for int() with base 10: 'Copy (3) of test'", "time": "2020-06-30T17:34:54.364671", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'Copy (3) of test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:54.645331", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:54.846435", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:55.056690", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:55.417137", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:55.581454", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:55.750424", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:55.879777", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'trace.axd'", "time": "2020-06-30T17:34:56.033185", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'trace.axd'"}
{"message": "invalid literal for int() with base 10: '.htaccess'", "time": "2020-06-30T17:34:56.270829", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: '.htaccess'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:56.421337", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:56.577675", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:56.832106", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:57.015833", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:57.165645", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:57.299304", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:57.436301", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-06-30T17:34:57.608173", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: '.env'", "time": "2020-06-30T17:34:57.819184", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: '.env'"}
{"message": "invalid literal for int() with base 10: '123456akhj'", "time": "2020-07-02T13:55:35.733620", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: '123456akhj'"}
{"message": "invalid literal for int() with base 10: '123456akhj'", "time": "2020-07-02T13:56:35.779631", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: '123456akhj'"}
{"message": "invalid literal for int() with base 10: '123456akhj'", "time": "2020-07-02T14:00:39.019864", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: '123456akhj'"}
{"message": "invalid literal for int() with base 10: '123456akhj'", "time": "2020-07-02T14:40:19.420001", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: '123456akhj'"}
{"message": "data must be bytes", "time": "2020-07-02T14:40:19.423183", "level": "DEBUG", "filename": "encryption.py", "funcName": "encryption_def", "module": "encryption", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/data_confidentiality/encryption/encryption.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/data_confidentiality/encryption/encryption.py\", line 25, in encryption_def\n    ciphertext = encryption_object.encrypt(data)\n  File \"/Users/jimburer/Git/cryptography/.venv/lib/python3.8/site-packages/cryptography/fernet.py\", line 52, in encrypt\n    return self._encrypt_from_parts(data, current_time, iv)\n  File \"/Users/jimburer/Git/cryptography/.venv/lib/python3.8/site-packages/cryptography/fernet.py\", line 55, in _encrypt_from_parts\n    utils._check_bytes(\"data\", data)\n  File \"/Users/jimburer/Git/cryptography/.venv/lib/python3.8/site-packages/cryptography/utils.py\", line 31, in _check_bytes\n    raise TypeError(\"{} must be bytes\".format(name))\nTypeError: data must be bytes"}
{"message": "invalid literal for int() with base 10: '123456akhj'", "time": "2020-07-02T14:41:29.858112", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: '123456akhj'"}
{"message": "invalid literal for int() with base 10: '123456akhj'", "time": "2020-07-02T16:09:57.669564", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: '123456akhj'"}
{"message": "invalid literal for int() with base 10: '123456akhj'", "time": "2020-07-02T18:21:51.202811", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: '123456akhj'"}
{"message": "invalid literal for int() with base 10: 'dsjh;ljahsdfkjh'", "time": "2020-07-02T18:30:13.252656", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'dsjh;ljahsdfkjh'"}
{"message": "invalid literal for int() with base 10: 'dsjh;ljahsdfkjh7666'", "time": "2020-07-02T18:30:20.301115", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'dsjh;ljahsdfkjh7666'"}
{"message": "invalid literal for int() with base 10: 'dsjh;ljahsdfkjh7666'", "time": "2020-07-02T18:38:57.273374", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'dsjh;ljahsdfkjh7666'"}
{"message": "invalid literal for int() with base 10: 'dsjh;ljahsdfkjh7666'", "time": "2020-07-02T18:40:06.471086", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'dsjh;ljahsdfkjh7666'"}
{"message": "invalid literal for int() with base 10: 'dsjh;ljahsdfkjh7666'", "time": "2020-07-02T18:41:32.456331", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'dsjh;ljahsdfkjh7666'"}
{"message": "invalid literal for int() with base 10: 'dsjh'", "time": "2020-07-02T18:41:40.112923", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'dsjh'"}
{"message": "invalid literal for int() with base 10: '<a value>'", "time": "2020-07-02T18:42:32.653658", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: '<a value>'"}
{"message": "invalid literal for int() with base 10: '<a value>'", "time": "2020-07-02T18:45:27.847572", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: '<a value>'"}
{"message": "invalid literal for int() with base 10: '<a value>'", "time": "2020-07-02T18:54:25.129657", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: '<a value>'"}
{"message": "invalid literal for int() with base 10: '<a value>'", "time": "2020-07-02T18:54:49.026539", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: '<a value>'"}
{"message": "invalid literal for int() with base 10: '<a value>'", "time": "2020-07-02T19:43:25.839279", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: '<a value>'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-07-02T19:47:10.748159", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/Git/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'password'", "time": "2020-07-03T17:55:02.731023", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/GitHub/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/GitHub/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'password'"}
{"message": "invalid literal for int() with base 10: 'password'", "time": "2020-07-03T18:02:25.975084", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/GitHub/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/GitHub/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'password'"}
{"message": "int() argument must be a string, a bytes-like object or a number, not 'AuthenticatorStorageForm'", "time": "2020-07-03T18:26:54.865621", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/GitHub/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/GitHub/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nTypeError: int() argument must be a string, a bytes-like object or a number, not 'AuthenticatorStorageForm'"}
{"message": "'AuthenticatorStorageForm' object has no attribute 'encode'", "time": "2020-07-03T18:26:54.866330", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/GitHub/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/GitHub/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 13, in byte_conversion_def\n    as_bytes = in_bytes.encode('utf-8')\nAttributeError: 'AuthenticatorStorageForm' object has no attribute 'encode'"}
{"message": "a bytes-like object is required, not 'NoneType'", "time": "2020-07-03T18:26:54.866526", "level": "DEBUG", "filename": "derived_secure_hash.py", "funcName": "derived_secure_hash_def", "module": "derived_secure_hash", "pathname": "/Users/jimburer/GitHub/cryptography/python_library/data/data_transformation/data_confidentiality/hash/secure_hash/derived_secure_hash/derived_secure_hash.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/GitHub/cryptography/python_library/data/data_transformation/data_confidentiality/hash/secure_hash/derived_secure_hash/derived_secure_hash.py\", line 42, in derived_secure_hash_def\n    dk = hashlib.pbkdf2_hmac(secure_hash_algorithm_name, authenticator_as_bytes, random_number_as_bytes, iterations, derived_secure_hash_length)\nTypeError: a bytes-like object is required, not 'NoneType'"}
{"message": "int() argument must be a string, a bytes-like object or a number, not 'AuthenticatorStorageForm'", "time": "2020-07-03T18:27:22.652628", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/GitHub/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/GitHub/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nTypeError: int() argument must be a string, a bytes-like object or a number, not 'AuthenticatorStorageForm'"}
{"message": "'AuthenticatorStorageForm' object has no attribute 'encode'", "time": "2020-07-03T18:27:22.652914", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/GitHub/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/GitHub/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 13, in byte_conversion_def\n    as_bytes = in_bytes.encode('utf-8')\nAttributeError: 'AuthenticatorStorageForm' object has no attribute 'encode'"}
{"message": "a bytes-like object is required, not 'NoneType'", "time": "2020-07-03T18:27:22.653069", "level": "DEBUG", "filename": "derived_secure_hash.py", "funcName": "derived_secure_hash_def", "module": "derived_secure_hash", "pathname": "/Users/jimburer/GitHub/cryptography/python_library/data/data_transformation/data_confidentiality/hash/secure_hash/derived_secure_hash/derived_secure_hash.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/GitHub/cryptography/python_library/data/data_transformation/data_confidentiality/hash/secure_hash/derived_secure_hash/derived_secure_hash.py\", line 42, in derived_secure_hash_def\n    dk = hashlib.pbkdf2_hmac(secure_hash_algorithm_name, authenticator_as_bytes, random_number_as_bytes, iterations, derived_secure_hash_length)\nTypeError: a bytes-like object is required, not 'NoneType'"}
{"message": "invalid literal for int() with base 10: 'this new password'", "time": "2020-07-03T18:58:53.948937", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/GitHub/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/GitHub/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'this new password'"}
{"message": "invalid literal for int() with base 10: 'testes'", "time": "2020-07-03T18:59:38.392239", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/GitHub/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/GitHub/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'testes'"}
{"message": "invalid literal for int() with base 10: 'password'", "time": "2020-07-03T19:18:01.242203", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/GitHub/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/GitHub/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'password'"}
{"message": "invalid literal for int() with base 10: 'password'", "time": "2020-07-03T19:29:25.197032", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/GitHub/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/GitHub/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'password'"}
{"message": "invalid literal for int() with base 10: 'password'", "time": "2020-07-03T19:36:53.655758", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/GitHub/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/GitHub/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'password'"}
{"message": "invalid literal for int() with base 10: 'password'", "time": "2020-07-03T20:19:38.694163", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/GitHub/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/GitHub/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'password'"}
{"message": "invalid literal for int() with base 10: 'password'", "time": "2020-07-03T20:20:11.727130", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/GitHub/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/GitHub/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'password'"}
{"message": "invalid literal for int() with base 10: 'password'", "time": "2020-07-03T20:22:21.782383", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/GitHub/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/GitHub/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'password'"}
{"message": "invalid literal for int() with base 10: 'myp@$$w0rd'", "time": "2020-07-07T13:28:09.928659", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/GitHub/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/GitHub/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'myp@$$w0rd'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-07-07T13:42:01.199168", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/GitHub/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/GitHub/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'test'", "time": "2020-07-07T13:43:50.097549", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/GitHub/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/GitHub/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'test'"}
{"message": "invalid literal for int() with base 10: 'newone'", "time": "2020-07-07T13:44:31.766223", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/GitHub/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/GitHub/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'newone'"}
{"message": "invalid literal for int() with base 10: 'anotherone'", "time": "2020-07-07T13:44:44.466683", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/GitHub/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/GitHub/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'anotherone'"}
{"message": "invalid literal for int() with base 10: 'p@ssw0rd'", "time": "2020-07-07T19:48:07.704829", "level": "DEBUG", "filename": "byte_conversion.py", "funcName": "byte_conversion_def", "module": "byte_conversion", "pathname": "/Users/jimburer/GitHub/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py", "exc_info": "Traceback (most recent call last):\n  File \"/Users/jimburer/GitHub/cryptography/python_library/data/data_transformation/type_conversion/byte_conversion.py\", line 6, in byte_conversion_def\n    in_bytes_as_int = int(in_bytes)\nValueError: invalid literal for int() with base 10: 'p@ssw0rd'"}
